- hosts: localhost
  environment:
    http_proxy: http://web-proxy.in.hpecorp.net:8080
    http_proxy: http://web-proxy.in.hpecorp.net:8080
    no_proxy: 192.168.67.7,192.168.67.5
  
  tasks:

  - name: Delete Schedule from source
    hpe3par_snapshot:
      storage_system_ip: 192.168.67.7
      storage_system_password: 3pardata
      storage_system_username: 3paradm
      state: schedule_delete
      schedule_name: my_ansible_sc     
        
